module.exports = {
    env: process.env.NODE_ENV,
    port: process.env.PORT,
    cors: process.env.CORS_ORIGIN,
    JWT_ACCESS_SECRET: process.env.JWT_ACCESS_SECRET,
    JWT_REFRESH_SECRET: process.env.JWT_REFRESH_SECRET,
    JWT_ACCESS_LIFETIME: process.env.JWT_ACCESS_LIFETIME,
    JWT_REFRESH_LIFETIME: process.env.JWT_REFRESH_LIFETIME,
    JWT_ALL_SECRET: process.env.JWT_ALL_SECRET,
    sendgridApiKey: process.env.SENDGRID_API_KEY,
    FE_URL: process.env.FE_URL,
    APP_NAME: process.env.APP_NAME,
    postgresqlUrl: process.env.POSTGRESQL_URL,
    staticUrl: process.env.STATIC_HOST,
    redis: {
        host: process.env.REDIS_HOST,
        port: process.env.REDIS_PORT,
        password: process.env.REDIS_PASSWORD,
    },
    S3_BUCKET: process.env.S3_BUCKET,
    AWS_ACCESS_KEY: process.env.AWS_ACCESS_KEY,
    AWS_SECRET_KEY: process.env.AWS_SECRET_KEY,
    AWS_REGION: process.env.AWS_REGION,
    STATIC_HOST: process.env.STATIC_HOST,
}
